<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Yogesh-Personal" failures="1" tests="2" name="Default test(failed)" time="22.439" errors="0" timestamp="2022-06-16T17:50:36 IST">
  <testcase classname="TestCases.DuplicateLoginTest" name="loginToAppTest" time="3.316"/>
  <testcase classname="TestCases.DuplicateLoginTest" name="verifyKiteLogoTest" time="0.156">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.DuplicateLoginTest.verifyKiteLogoTest(DuplicateLoginTest.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyKiteLogoTest -->
  <testcase classname="TestCases.DuplicateLoginTest" name="verifyTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="TestCases.DuplicateLoginTest" name="verifyZerodhaLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyZerodhaLogoTest -->
</testsuite> <!-- Default test(failed) -->
